-- AlterTable
ALTER TABLE "order_items" ALTER COLUMN "name" SET DATA TYPE VARCHAR(500);

-- AlterTable
ALTER TABLE "products" ALTER COLUMN "name" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "slug" SET DATA TYPE VARCHAR(500);
